In [2]:
import numpy as np

In [23]:
a = np.array([1,2,4,5,3,9])

In [5]:
b = np.array([9,8,6,5,7,1])

In [6]:
a + b

array([10, 10, 10, 10, 10, 10])

In [5]:
np.array([[1,2,3],
        [3,4,5]])

array([[1, 2, 3],
       [3, 4, 5]])

In [3]:
np.zeros(15,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(15,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
a*b #no es un producto punto

array([ 9, 16, 24, 25, 21,  9])

In [15]:
a.sum()

24

In [16]:
a.max()

9

In [17]:
a.min()

1

In [18]:
a.argmax()

5

In [19]:
a.argmin()

0

In [20]:
a.mean()

4.0

In [21]:
a.std()

2.581988897471611

In [3]:
c = np.arange(1,8,2)

In [4]:
c

array([1, 3, 5, 7])

In [26]:
d = np.linspace(1,8,4)

In [27]:
d

array([1.        , 3.33333333, 5.66666667, 8.        ])

In [30]:
np.random.randint(5,20,size = 10)

array([16,  8, 10,  5,  8, 13, 19, 11, 15, 11])

In [6]:
C = np.array([(3,2,5),(4,5,6)])

array([[3, 2, 5],
       [4, 5, 6]])

In [33]:
B = np.array([(1,1,1),(0,0,0)])

In [34]:
D = np.array([(1,3,4),(4,5,5),(8,9,6)])

In [35]:
print(B)

[[1 1 1]
 [0 0 0]]


In [36]:
B + C

array([[4, 3, 6],
       [4, 5, 6]])

In [37]:
B*C

array([[3, 2, 5],
       [0, 0, 0]])

In [38]:
B*D #No es multiplicacion matricial

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [39]:
A = np.array([(4,5,6,5),(1,5,6,4),(1,4,6,7)])

In [40]:
A

array([[4, 5, 6, 5],
       [1, 5, 6, 4],
       [1, 4, 6, 7]])

In [44]:
A[0]

array([4, 5, 6, 5])

In [45]:
A[2,1]

4

In [48]:
A[0:3,1]

array([5, 5, 4])

In [49]:
A[:,1]

array([5, 5, 4])

In [50]:
A[:,1:3]

array([[5, 6],
       [5, 6],
       [4, 6]])

## Tarea: Definir un producto matricial usando numpy y for

In [51]:
A

array([[4, 5, 6, 5],
       [1, 5, 6, 4],
       [1, 4, 6, 7]])

In [52]:
A.sum()

54

In [54]:
A.argmax()

11

In [55]:
A.mean()

4.5

In [57]:
A.mean(axis = 1)

array([5. , 4. , 4.5])

##Hacer un codigo que resuelva sistemas de ecuaciones lineales

In [3]:
len(A(axis = 1))

NameError: name 'A' is not defined